### PR TITLE
(DRAFT) Use local units based on iRacing prefs

### PR DESCRIPTION
**Pull request by flexgrip**
Hey Andreas.

I wanted to make sure my PRs preserve your format and make sense.

So I cloned your repo and symlinked it into my simhub directory. Opened up dash studio and made a small change. Basically just fixed the label on the speed box so that MPH users see their local unit under the speed. Figured it was a simple change since your dash is already using local units.

Anyway, this is the resulting commit. I don't see much, but I do see where it moved some layer sizing around. I tried exporting and re-importing the dash. But can you tell me if this is an acceptable change? By that I mean, should a small change like that cause this sort of diff?

### CODE REVIEW

**Comment by flexgrip** [comment]
Added conversion to show track temps in local format too. Should be seamless and use whatever choice they selected in iRacing.

**Comment by andreasdahl1987** [comment]
I'll have a look, good idea to implement this! Also, I see you found some instances of the AllTimeBest property being used, I thought I had found them all :D The layer sizing I dont know, it is a bit cryptic to me how this all works. I notice myself that small changes result in several files making minor adjustments

**Comment by flexgrip** [comment]
Yeah I was doing this by just editing in dash studio. But I could probably just find the formula changes in the json files snd change only that. I wonder if that is worth giving up the ease of use though. Maybe dash studio just constantly makes small changes like you say.

**Comment by flexgrip** [comment]
Ohh I see. A lot of the trouble is that the files are saved in like a minified format. Maybe we can ask wotover to not do that.

**Comment by flexgrip** [comment]
Ok summary of questions then.

1. Should we ask wotover to implement a pretty/linter or whatever for json? We could run it ourselves. I see the github action you have for it. But that seems weird to do.
2. In scenarios like this, where I am just changing a formula. Should I just grep for that formula and then change it manually? That way PR's like this are just for 1 line changes?
3. How should we test changes? Just run it ourselves and see what happens? If so, is there anything we need to look for to match the device support you want? Like resolution changes and such?

**Comment by andreasdahl1987** [comment]
> Ohh I see. A lot of the trouble is that the files are saved in like a minified format. Maybe we can ask wotover to not do that.

@mcowger is back from holiday monday, he'll have a look at what went wrong with our pretty-thingie. Suddenly just stopped working, might be because of simhub updates? If it is prone to crashing I think we should ask wotever 👍

**Comment by andreasdahl1987** [comment]
> Ok summary of questions then.
> 
> 1. Should we ask wotover to implement a pretty/linter or whatever for json? We could run it ourselves. I see the github action you have for it. But that seems weird to do.
> 2. In scenarios like this, where I am just changing a formula. Should I just grep for that formula and then change it manually? That way PR's like this are just for 1 line changes?
> 3. How should we test changes? Just run it ourselves and see what happens? If so, is there anything we need to look for to match the device support you want? Like resolution changes and such?

1. Yeah maybe it can be implemented even with the compression thingie going on?
2. I think for stability all changes should be made in the dashboard editor. Looks like compensatory changes are automatically added by the editor.
3. I think the best approach for a PR would be adding screenshots of the changes to get a rough feedback, and if thinks look good for testing Ill just check the PR on my rig and see if it works as I want it. At the moment, the dash is a fixed size, and not optimized for VoCore either, so the reference is a 800 x 480 HDMI screen.

**Comment by flexgrip** [comment]
Oh I see what @mcowger was doing. If the repo always runs json pretty print then we won’t have these crazy huge diffs for some stuff.

Let me know if you need help fixing it.

**Comment by andreasdahl1987** [comment]
Uhm, prettier is still bugging out. Might have to rebase this PR? Or make a new one? @mcowger  what do you think?

**Comment by mcowger** [comment]
Yes, this would need a rebase because it based on a version using prettier 4.2

**Comment by flexgrip** [comment]
> Yes, this would need a rebase because it based on a version using prettier 4.2

Sorry. Been busy.

I will rebase and cut a new PR for this. And run the prettier locally.

Got a bunch of other experimental things I want to do.

**Pull request closed without merging**
