### PR TITLE
Implementation of ShowMapEnabled.

### PR DESCRIPTION
**Pull request by photon1503**
Only gear.djson has been changed.

You will find a deletion of \DahlDesignDDU in the commit - this was my version of the symbolic link for the folder before Matt's version was created.

I also added the _Backup folder to .gitignore

### CODE REVIEW

**Comment by mcowger** [comment]
This is working well for me.

**Comment by andreasdahl1987** [comment]
@photon1503  Tested, working fine. But I did some changes to the plugin and the dashboard to make it easier to work with this feature. The setting now just sets the `dashType` to `"Map"`, and I've made a new element in the gears tab which is the map. It was easier to just take one instance of your map than to remove all of them.

**Comment by andreasdahl1987** [comment]
By the way, now that backups have added to the gitignore, should I just delete the backup folder from the repo?

**Comment by mcowger** [comment]
Sure, seems reasonable.

**Comment by photon1503** [comment]
> @photon1503 Tested, working fine. But I did some changes to the plugin and the dashboard to make it easier to work with this feature. The setting now just sets the `dashType` to `"Map"`, and I've made a new element in the gears tab which is the map. It was easier to just take one instance of your map than to remove all of them.

@andreasdahl1987 : I understand, but do we still have the option to show the map and also to change the DashType (i.e. GT3/BiasOnly/etc.)?

**Comment by andreasdahl1987** [comment]
@photon1503 Checking the map setting will override the dashtype. So the dash type property will not be GT3 even though you're in a GT3 with automatic dash selection. Now that you mention this, it might be better to keep the property solution, and have the map set up like now, but visibility controlled by the that property, and not by dashtype property. Some cars have other elements (like supercar launch screen) that rely on the dashtype property for visibility. I can edit this for a 1.9.1 in the evening.

**Pull request closed without merging**
