### PR TITLE
Add secondary gear display when Map Mode enabled in Speed Section

### PR DESCRIPTION
**Pull request by mcowger**
When map mode is enabled, slight rearrange the speed section to show the current gear there.
Screen Shot 2022-11-02 at 6 26 09 PM
Screen Shot 2022-11-02 at 6 26 26 PM

### CODE REVIEW

**Comment by andreasdahl1987** [comment]
First of all, this way of working with the dashboard is just revolutionary. Thanks @mcowger  for setting this up. Can you move the max speed a bit closer to the dividing line? 

image

Also, if you look at version 1.8.0, do you have any issues with the timers on T1 (left side display)? Particulary the one showing current lap time. My Segoe UI font had suddenly changed, became fatter and the numbers not uniform in width - so the numbers bouncing back and forth as the combined width of the text changes. I changed to Segoe UI Historical (and made it semi bold) in 1.9.0. Did that change anything for you? I might have to change the font of all elements to historical.

**Comment by andreasdahl1987** [comment]
Something that could go very well together with this is a mappable button in the properties plugin that flips `Settings.ShowMapEnabled`. What do you think?

Could also set that up in the PitMenu. Such as PitMenu10, which has system volume +/-, which maybe isn't all that relevant. Could set map to PitMenu10 + "+" and Pit screen to PitMenu10 + "-". And then have fuel toggle on both PitMenu7 and PitMenu8.

**Comment by mcowger** [comment]
Fair comments on both.

Will update commit tonight.

**Comment by mcowger** [comment]
Fair comments on both.

Will update commit tonight.

I'm not seeing anything unexpected with Fonts...

**Comment by andreasdahl1987** [comment]
> Fair comments on both.
> 
> Will update commit tonight.
> 
> I'm not seeing anything unexpected with Fonts...

Ok, good to know I guess. Is there any difference between Segoe UI and Segoe UI Historic for you?

**Comment by mcowger** [comment]
Moved the max speed.  Will add the option in a separate PR.

**Comment by mcowger** [comment]
> Is there any difference between Segoe UI and Segoe UI Historic for you?

There is a reason my work doesn't let me do UI work :).   I can't really notice these differences :).

**Comment by andreasdahl1987** [comment]
Great :D

**Pull request merged**
