### PR TITLE
Added Brake and Throttle Gauges

### PR DESCRIPTION
**Pull request by photon1503**
As discussed, new Brake/Throttle Gauges in the center screen.

* New setting in Misc to enable visibility
* New action in Control to add binding for toggling the visibility
* Reorderd Map to top again, but deleted the unnecessary rectangle which was opaque.
* Set opacity of map to 70%

Animation

### CODE REVIEW

**Comment by andreasdahl1987** [comment]
Humm, conflicts with main branch now?

**Comment by photon1503** [comment]
I have seen the conflict, too. But maybe because of this compressed json format? 

Maybe @mcowger can check?

**Comment by photon1503** [comment]
I formatted both json files and compared them.

Apart from my change, something changed in the header. No idea where this comes from :-(
Should I replace the ID with the old one?

image

**Comment by photon1503** [comment]
I think https://github.com/andreasdahl1987/DahlDesignDash/commit/2a85773ed36e2ca0e13870211b493c84cc8c12f2 which was commited 2 hours ago conflicts with my change.

Let me check this tomorrow

**Comment by andreasdahl1987** [comment]
I have no clue what this ID does. Does the dashboard work if you change it?

**Comment by mcowger** [comment]
The placement line probably just records the last place the window was.  

The ID is probably a GUID: https://betterexplained.com/articles/the-quick-guide-to-guids/

It's likely safe to just accept those changes.

**Comment by andreasdahl1987** [comment]
Ok I need to be on the computer to merge this with commandline. Ill make a test branch first

**Comment by photon1503** [comment]
I can redo my change based on the current branch. My fork was out of sync, that's where the conflict comes from. Can do it in the evening today

**Pull request closed without merging**
