### PR TITLE
Change/delta screens

### PR DESCRIPTION
**Pull request by andreasdahl1987**
@mcowger @photon1503 

Changed the LastLap delta screen to have bars going above / below the line with some color coding. 

Let me know what you think and I'll change the other two.

### CODE REVIEW

**Comment by photon1503** [comment]
@andreasdahl1987 do you have some screenshots?

**Comment by andreasdahl1987** [comment]
Old:
image
New:
image

**Comment by andreasdahl1987** [comment]
Doing the editing in IDE instead of simhub editor probably saved me 2 hours:D

**Comment by photon1503** [comment]
cool, I like the new design

**Pull request merged**
