### PR TITLE
Adjust Pit Menu Help to make it clear which controls do what.

### PR DESCRIPTION
**Pull request by mcowger**
Screen Shot 2022-11-05 at 12 13 12 PM

### CODE REVIEW

**Comment by andreasdahl1987** [comment]
It is difficult to tell if this PR will revert the changes made in #9. This PR doesnt seem to include the changes in #9, but there is no conflicts. I assume #9 will be erased my merging this?

**Comment by mcowger** [comment]
It should not, as it would warn about that.  I only included the edits to the pit settings json.

**Comment by andreasdahl1987** [comment]
Ok, so what is extracted from the PR is only the changes you made to the branch you started on, not the total difference between the PR branch and the main branch?

**Comment by andreasdahl1987** [comment]
Lets try merging and see what happens

**Comment by andreasdahl1987** [comment]
You're right, only the things you added got in there 👍

**Pull request merged**
